[env:m5stack-grey]
platform = espressif32
board = m5stack-grey
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
board_build.partitions = default_16MB.csv
lib_deps =
    m5stack/M5Unified
    meganetaaan/M5Stack-Avatar
    bblanchon/ArduinoJson
build_flags =
    -DCORE_DEBUG_LEVEL=0
